name: Publish on PyPI

on: [push]

jobs:
  Publish_on_PyPI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Building
        run: |
          python -m pip install build
          python -m build
      - name: ls
        run: ls
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
